/* =====================================================================
   CASTING-APP · Wörterbuch Englisch für die Steuerseite (siehe i18n.js)
   Links der deutsche Text, wie er im Code steht, rechts die Übersetzung.
   "{}" = eingesetzter Wert. Neuer Text in der Steuerseite → hier ergänzen
   (tests/test_control_page.py meldet deutsche Reste in der englischen Ansicht).
   ===================================================================== */
window.CastLanguages = window.CastLanguages || {};
window.CastLanguages.en = {
 "Verbindungen & Zugänge": "Connections & access",
 "OBS · FACEIT · DACH CS · Musik": "OBS · FACEIT · DACH CS · Music",
 "Daten & Sicherung": "Data & backup",
 "Ordner, Sichern, Laden": "Folders, back up, load",
 "Über die App": "About the app",
 "Version, Lizenz, Hilfe": "Version, license, help",
 "Gilt für die App auf diesem PC – nicht fürs Match.": "Applies to the app on this PC – not to the match.",
 "Womit die App spricht. Schlüssel liegen im Schlüsselbund des Systems und werden nach dem Speichern nie wieder angezeigt – nur ersetzen oder löschen.": "What the app talks to. Keys are kept in the system keychain and never shown again after saving – only replaced or deleted.",
 "Musik · Spotify über Tuna": "Music · Spotify via Tuna",
 "So sind deine Zugänge geschützt": "How your access data is protected",
 "Gespeichert im Schlüsselbund des Systems – keine Datei, kein Export.": "Stored in the system keychain – no file, no export.",
 "Nach dem Speichern nie wieder angezeigt – nur ersetzen oder löschen.": "Never shown again after saving – only replace or delete.",
 "Nie in Overlays, Log, Sitzungs- oder Theme-Exporten.": "Never in overlays, log, session or theme exports.",
 "Der Server der App hört nur auf diesem PC.": "The app's server only listens on this PC.",
 "Schlüssel gespeichert": "key saved",
 "kein Schlüssel": "no key",
 "Zugang gespeichert": "access saved",
 "nicht eingerichtet": "not set up",
 "an": "on",
 "aus": "off",
 "Größe automatisch": "automatic size",
 "Größe passt sich dem Fenster an (1920 px = 100 %, 2560 px = 130 %)": "Size follows the window (1920 px = 100 %, 2560 px = 130 %)",
 "Alles speichert sich von selbst. Für einen anderen PC oder als Sicherung: den ganzen Stand als Datei sichern und dort laden.": "Everything saves itself. For another PC or as a backup: save the whole state as a file and load it there.",
 "Videos und eigene Schriften liegen in deinen Dokumenten, Einstellungen und Log im Datenordner:": "Videos and your own fonts are in your documents, settings and log in the data folder:",
 "– Overlays und Steuerung für CS2-Casts mit OBS.": "– overlays and control for CS2 casts with OBS.",
 "Frei verwendbar (Public Domain, siehe LICENSE). Mitgelieferte Schriften und Programme haben eigene Lizenzen (Ordner LICENSES).": "Free to use (public domain, see LICENSE). Bundled fonts and programs have their own licenses (folder LICENSES).",
 "Projekt auf GitHub": "Project on GitHub",
 "Fehler melden": "Report a bug",
 "FACEIT-Schlüssel:": "FACEIT key:",
 "Nutzer-ID und Key:": "User ID and key:",
 "⚙ App-Einstellungen → Verbindungen & Zugänge": "⚙ App settings → Connections & access",
 "Restzeit-Balken unter dem Logo (zeigt, wann der nächste Sponsor kommt)": "Countdown bar under the logo (shows when the next sponsor comes)",
 "Auf Active Duty zurücksetzen": "Reset to Active Duty",
 "Eigenes Bild: Klick auf das Bild.": "Own picture: click the picture.",
 "Holt Name und Vorschaubild von Steam – nur die Workshop-Nummer geht dorthin.": "Gets name and preview picture from Steam – only the workshop number is sent there.",
 "Name der Map": "Name of the map",
 "Reicht für:": "Enough for:",
 "Workshop-Link oder ID einfügen": "Paste workshop link or ID",
 "Im Pool": "In the pool",
 "Weitere Maps": "More maps",
 "· Ziehen = Reihenfolge im Veto · Schalter = im Pool": "· Drag = order in the veto · Switch = in the pool",
 "· Schalter an = kommt in den Pool": "· Switch on = goes into the pool",
 "+ Eigene Map": "+ Own map",
 "Aus dem Workshop holen": "Get from the Workshop",
 "Von Hand: Name + Bild": "By hand: name + picture",
 "· {} Maps": "· {} maps",
 "entspricht Active Duty (Season 5)": "matches Active Duty (Season 5)",
 "eigener Pool – weicht von Active Duty ab": "own pool – differs from Active Duty",
 "{} – {} Map(s) fehlen": "{} – {} map(s) missing",
 "{} Schritte im Ablauf": "{} steps in the sequence",
 "Frage Steam …": "Asking Steam …",
 "Steam antwortet nicht": "Steam does not answer",
 "✓ „{}“ ist im Pool.": "✓ “{}” is in the pool.",
 "Nicht im Workshop gefunden – stimmt der Link?": "Not found in the Workshop – is the link right?",
 "Das ist kein Workshop-Link – er endet auf „?id=“ und einer Zahl.": "That is not a Workshop link – it ends with “?id=” and a number.",
 "Steam ist gerade nicht erreichbar – Name und Bild von Hand eintragen.": "Steam cannot be reached right now – enter name and picture by hand.",
 "Vorschaubild liegt nicht bei Steam": "Preview picture is not hosted by Steam",
 "Vorschaubild ist kein Bild": "Preview picture is not a picture",
 "Antwort von Steam zu groß": "Answer from Steam too large",
 "BIBLIOTHEK – alle Videos im Videos-Ordner · Haken = in der gewählten Playlist": "LIBRARY – all videos in the videos folder · tick = in the chosen playlist",
 "Blau = in diesen Szenen läuft sie von selbst. Clips laufen nur, wenn du sie in Live startest.": "Blue = it runs by itself in these scenes. Clips only run when you start them in Live.",
 "Diese Playlist ab jetzt immer für diese Szene": "Use this playlist for this scene from now on",
 "Einmal durch, mit Ton – danach wieder der Hintergrund.": "Once through, with sound – then back to the background.",
 "Für die Szene merken": "Keep for this scene",
 "Läuft endlos, nahtlos verbunden.": "Runs endlessly, seamlessly joined.",
 "Läuft von selbst in (Ingame nie – dort liegt das Spielbild)": "Runs by itself in (never Ingame – the game picture is there)",
 "Nacheinander oder zufällig, dann von vorn.": "In order or shuffled, then from the start.",
 "Noch keine Videos – unten in der Bibliothek anhaken.": "No videos yet – tick them in the library below.",
 "Playlist löschen": "Delete playlist",
 "Ton der Videos abspielen": "Play the videos' sound",
 "Video – es läuft das erste": "Video – the first one runs",
 "Videos – Reihenfolge mit ↑ ↓": "Videos – order with ↑ ↓",
 "Zufällig": "Shuffled",
 "Nacheinander": "In order",
 "alle Szenen außer Ingame": "all scenes except Ingame",
 "Über Schwarz": "Through black",
 "Spielt OBS ab, ist der Übergang zwischen zwei Videos ein Schnitt. Clips spielt immer das Overlay (mit Ton).": "When OBS plays, the change between two videos is a cut. Clips are always played by the overlay (with sound).",
 "Hintergrund (Playlisten)": "Background (playlists)",
 "PLAYLISTEN": "PLAYLISTS",
 "+ Playlist": "+ Playlist",
 "Neue Playlist": "New playlist",
 "Art": "Kind",
 "Ein Video · Dauerschleife": "One video · endless loop",
 "Mehrere Videos": "Several videos",
 "Clips": "Clips",
 "Übergang zwischen den Videos": "Transition between the videos",
 "Dauer (Sek.)": "Duration (sec.)",
 "Reihenfolge": "Order",
 "HINTERGRUND": "BACKGROUND",
 "Hintergrund dieser Szene": "Background of this scene",
 "Kein Hintergrund": "No background",
 "Clip zeigen": "Show clip",
 "Clip stoppen": "Stop clip",
 "Clip-Playlist": "Clip playlist",
 "{} · Standard": "{} · default",
 "{} Video(s) · {}": "{} video(s) · {}",
 "Dauerschleife": "endless loop",
 "nacheinander": "in order",
 "auf Abruf in Live": "on demand in Live",
 "keine Szene": "no scene",
 "{} Szenen": "{} scenes",
 "Aus der Playlist nehmen": "Remove from the playlist",
 "Testdaten abspielen": "Play test data",
 "Testdaten stoppen": "Stop test data",
 "Ein kurzes Beispiel-Match nur in der Vorschau hier – so prüfst du Scoreboard und Team-Szenen ohne Spiel. Nie im Stream.": "A short sample match only in the preview here – check scoreboard and team scenes without a game. Never on stream.",
 "Szenen-Panels": "Scene panels",
 "Welche Felder jede Szene in Live im": "Which fields each scene brings in Live in the",
 "mitbringt. Grün = Feld ist dabei. Lila Name = angepasst, sonst Vorgabe.": ". Green = field is included. Purple name = customized, otherwise default.",
 "Auf Vorgabe": "To default",
 "Panel der Szene": "Scene panel",
 "Welche Felder diese Szene hier zeigt": "Which fields this scene shows here",
 "Felder für „{}“": "Fields for “{}”",
 "Felder für diese Szene wählen": "Choose fields for this scene",
 "Panel öffnet sich beim Szenenwechsel": "Panel opens when the scene changes",
 "Auf Vorgabe zurück": "Back to default",
 "Vorgabe": "default",
 "angepasst": "customized",
 "Keine Szene im Programm.": "No scene in the program.",
 "Spielstand": "Score",
 "Texte im Overlay": "Texts in the overlay",
 "Notiz": "Note",
 "nur für dich – nie im Stream": "only for you – never on stream",
 "z. B. Timeout Team B noch 1×": "e.g. Team B has 1 timeout left",
 "Noch keine Maps – erst das Map-Veto ausfüllen.": "No maps yet – fill in the map veto first.",
 "Noch keine Sponsoren für dieses Theme – Setup → Sponsoren.": "No sponsors for this theme yet – Setup → Sponsors.",
 "Format": "Format",
 "Format des Vetos": "Format of the veto",
 "Schritte, Teams und Presets bearbeiten → Match": "Edit steps, teams and presets → Match",
 "Für diese Szene gibt es hier nichts einzustellen.": "Nothing to set here for this scene.",
 "Seite des Gegners": "Side of the opponent",
 "Das Veto beginnt mit dem neuen Format von vorn – eingetragene Bans und Picks werden geleert.": "The veto starts over with the new format – entered bans and picks are cleared.",
 "Teams tauschen": "Swap teams",
 "Anordnen": "Arrange",
 "Andocken": "Dock",
 "Aussehen & Oberfläche": "Appearance & interface",
 "Unten": "Bottom",
 "Oben": "Top",
 "Sprache": "Language",
 "Bereiche der Einstellungen": "Sections of the settings",
 "Ton der Quellen in OBS": "Audio of the sources in OBS",
 "Lautstärke, Stumm, Abhören und Lautstärke je Szene regelt die App direkt in OBS – wie im OBS-Mixer. Dafür muss die App mit OBS verbunden sein.": "The app controls volume, mute, monitoring and volume per scene directly in OBS – like the OBS mixer. For this the app must be connected to OBS.",
 "Mit OBS verbinden …": "Connect to OBS …",
 "Lautstärke je Szene merken": "Remember volume per scene",
 "Regler gelten jetzt für „{}“": "Sliders now apply to “{}”",
 "Szene auf Standard": "Scene back to standard",
 "eigene Lautstärke in dieser Szene": "own volume in this scene",
 "Diese Lautstärke gilt nur in der Szene „{}“": "This volume applies only in the scene “{}”",
 "Nur abhören (Ausgabe stumm)": "Monitor Only (mute output)",
 "Abhören und Ausgabe": "Monitor and Output",
 "Abhören {}": "Monitoring {}",
 "(0 = bleibt stehen)": "(0 = stays)",
 "(empfohlen)": "(recommended)",
 "(Hochformat). „Füllen\" schneidet passend zu, „Ganz\" zeigt das komplette Bild. FACEIT liefert Map-Bilder automatisch mit.": "(portrait). “Fill\" crops to fit, “Whole\" shows the complete image. FACEIT delivers map images automatically.",
 "(Kopie)": "(copy)",
 "(Live → Szenen). Neue Einblendungen:": "(Live → Scenes). New graphics:",
 "(oder ein anderer Link), ein": "(or any other link), a",
 "(Stats des beobachteten Spielers). „Automatisch“ beim Head-to-Head = stärkster Spieler je Team (Schaden pro Runde + 2 × (Kills − Tode)).": "(stats of the observed player). “Automatic” for head-to-head = strongest player per team (damage per round + 2 × (kills − deaths)).",
 "(Webcam / Capture-Karte), ein": "(webcam / capture card), an",
 "). Die Szenen wechselst du hier im Reiter Live – mit eigenem Übergang (Blende, Schieben, Wischen, Stinger in Theme-Farben). Kameras kommen dafür am besten per VDO.Ninja oder als Gerät (Kameras & Quellen).": "). You switch the scenes here in the Live tab – with their own transition (fade, slide, wipe, stinger in theme colours). Cameras come in best via VDO.Ninja or as a device (Cameras & sources).",
 "+ Bauchbinde": "+ Lower third",
 "+ Hinweis": "+ Notice",
 "+ Map-Fakt": "+ Map fact",
 "+ Map-Info": "+ Map info",
 "+ Neu": "+ New",
 "+ Neues Theme": "+ New theme",
 "+ Punktestand": "+ Score",
 "+ Schritt": "+ Step",
 "+ Spieler": "+ Player",
 "+ Spieler (live)": "+ Player (live)",
 ", bei „Füllen\"": ", with “Fill\"",
 ", Key fehlt noch": ", key still missing",
 ", wenn du in OBS eine eigene Quelle darüberlegst.": ", if you put your own source on top in OBS.",
 ". Die App sucht ihn in allen Steam-Bibliotheken.": ". The app looks for it in all Steam libraries.",
 ". „Füllen\" schneidet passend zu, „Ganz\" zeigt das komplette Bild. Mit FACEIT werden sie automatisch gefüllt.": ". “Fill\" crops to fit, “Whole\" shows the complete image. With FACEIT they are filled in automatically.",
 "1. „Szene ‚Cast – Sendung' in OBS anlegen\" klicken. 2. Unten die Szenen abhaken, die du benutzt – nur die erscheinen im Reiter": "1. Click “Szene ‘Cast – Sendung' in OBS anlegen\". 2. Tick the scenes you use below – only those appear in the tab",
 "ab, ist MP4 (H.264) oder WebM (VP9) am sichersten.": "plays them, MP4 (H.264) or WebM (VP9) is safest.",
 "Abbrechen": "Cancel",
 "Abdunkeln": "Darken",
 "Abgebrochen": "Cancelled",
 "Abgebrochen – in OBS wurde nichts geändert.": "Cancelled – nothing was changed in OBS.",
 "Abhören": "Monitoring",
 "Aktiver CS2-Pool + ältere Maps mit Bildern. Eigene Maps, Bilder und Map-Fakten gehen verloren.": "Active CS2 pool + older maps with images. Your own maps, images and map facts will be lost.",
 "Aktualisieren": "Refresh",
 "Aktuell:": "Current:",
 "Aktuelle Anordnung speichern als …": "Save current arrangement as …",
 "Aktuelle Map (automatisch)": "Current map (automatic)",
 "Akzent": "Accent",
 "Alle": "All",
 "alle 15 s aktualisieren": "refresh every 15 s",
 "Alle Anpassungen an diesem Theme (Farben, Logos, Schrift) gehen verloren.": "All changes to this theme (colours, logos, font) will be lost.",
 "Alle Bereiche aufklappen": "Expand all areas",
 "Alle Bereiche einklappen": "Collapse all areas",
 "Alle Einblendungen ausblenden": "Hide all graphics",
 "Alle eingetragenen Bans, Picks und Ergebnisse werden geleert.": "All entered bans, picks and results are cleared.",
 "Alle Ergebnisse löschen": "Delete all results",
 "Alle Ergebnisse löschen?": "Delete all results?",
 "Alle Gruppen": "All groups",
 "Alle Maps haben schon ein Bild. „im Veto\" = steht bei der Veto-Auswahl zur Verfügung (aktiver Pool). Eigenes Bild: Klick auf das Feld.": "All maps already have an image. “in veto\" = available in the veto (active pool). Your own image: click the field.",
 "Alle Maps leeren": "Clear all maps",
 "Alle Maps leeren?": "Clear all maps?",
 "Alle oben rechts": "All top right",
 "Alle Teams sind fertig – keine weitere Runde nötig.": "All teams are finished – no further round needed.",
 "Alle {}": "All {}",
 "Alles": "Everything",
 "Alles größer": "Zoom in",
 "Alles kleiner": "Zoom out",
 "Alles läuft in deiner einen Browserquelle („Cast – Overlay“). Die Inhalte (Teams, Spielstand, Tabelle …) steuerst du im DACH-CS-Live-Dashboard – die App schaltet die Seiten um, setzt Kameras und Inhalt in die Rahmen und legt ihre Einblendungen darüber.": "Everything runs in your one browser source (“Cast – Overlay”). You control the contents (teams, score, table …) in the DACH CS live dashboard – the app switches the pages, puts cameras and content into the frames and lays its graphics on top.",
 "Alles wird automatisch gespeichert": "Everything is saved automatically",
 "Alles zurücksetzen": "Reset everything",
 "Alles zurücksetzen?": "Reset everything?",
 "Als Arbeitsbereich speichern": "Save as workspace",
 "Als Datei sichern oder laden – z. B. für einen anderen PC:": "Back up to a file or load one – e.g. for another PC:",
 "Als eigene OBS-Tonquelle": "As its own OBS audio source",
 "als Knopf.": "as a button.",
 "als Knopf. Mit": "as a button. With",
 "Als Preset speichern": "Save as preset",
 "Als Tab zu": "As a tab to",
 "Am Zug": "Up next",
 "Andocken: links, unter oder neben der Vorschau": "Dock: left of, below or next to the preview",
 "Anlegen": "Create",
 "Anordnung": "Arrangement",
 "ANORDNUNG": "ARRANGEMENT",
 "Anordnung zurücksetzen": "Reset arrangement",
 "App nicht erreichbar.": "App not reachable.",
 "App-Einstellungen": "App settings",
 "App-Einstellungen öffnen": "Open app settings",
 "App-Einstellungen: OBS, Musik, Aussehen": "App settings: OBS, music, appearance",
 "ARBEITSBEREICH": "WORKSPACE",
 "Arbeitsbereich wechseln, speichern oder das Layout bearbeiten": "Switch or save a workspace, or edit the layout",
 "Arbeitsbereich „{}“ löschen?": "Delete workspace “{}”?",
 "Auf allen Laufwerken suchen": "Search all drives",
 "auf die App umgestellt": "switched to the app",
 "Auf diesem PC": "On this PC",
 "Auf einem anderen PC (Observer)": "On another PC (observer)",
 "Aus": "Off",
 "Aus dem Press Kit …": "From the press kit …",
 "Aus – die App nimmt nur Daten von diesem PC an.": "Off – the app only accepts data from this PC.",
 "aus- bzw. einschalten und OBS neu starten.": "off or on and restart OBS.",
 "Ausblenden": "Hide",
 "Ausblenden:": "Hide:",
 "Ausführen": "Run",
 "Aussehen": "Appearance",
 "Ausstehend": "Pending",
 "Automatisch (stärkster Spieler)": "Automatic (strongest player)",
 "Automatisch einrichten": "Set up automatically",
 "automatisch ergänzt.": "are added automatically.",
 "Außen gespiegelt (empfohlen)": "Mirrored outside (recommended)",
 "Balken": "Bars",
 "Bans, Picks und Ergebnisse werden entfernt, die Reihenfolge bleibt.": "Bans, picks and results are removed, the order stays.",
 "Bauchbinde": "Lower third",
 "Baum wie bei FACEIT": "bracket like FACEIT",
 "Bearbeiten": "Edit",
 "Beenden": "Quit",
 "Bei VDO.Ninja werden": "For VDO.Ninja",
 "Bei „Nur Fenster schließen“ laufen die Overlays in OBS weiter.": "With “Close window only” the overlays in OBS keep running.",
 "Beide Teams live aus CS2: K / D / ADR": "Both teams live from CS2: K / D / ADR",
 "Beim Start nach neuer Version suchen (fragt nur die Versionsnummer bei GitHub ab)": "Look for a new version at start (only asks GitHub for the version number)",
 "Beobachteter Spieler (folgt der Kamera)": "Observed player (follows the camera)",
 "BEREICH": "AREA",
 "Bereiche ziehen und andocken · Schloss auf den Trennlinien = Bereich bleibt fest · Größe an den Trennlinien ziehen": "Drag and dock areas · lock on the dividers = area stays fixed · drag the dividers to resize",
 "Bilanz": "Record",
 "Bild": "Image",
 "Bild wählen": "Choose image",
 "Bild wählen …": "Choose image …",
 "Bist du sicher?": "Are you sure?",
 "Bitte die Nutzer-ID eintragen (nur Ziffern, z. B. 123).": "Please enter the user ID (digits only, e.g. 123).",
 "Bitte einen FACEIT-Turnier-Link einfügen.": "Please paste a FACEIT tournament link.",
 "Bitte einen Pfad eingeben.": "Please enter a path.",
 "Bitte einen „Server side“-Key verwenden.": "Please use a “server side” key.",
 "Bitte kurz prüfen. Gelöscht wird nichts – vorhandene Quellen werden nur auf die App umgestellt.": "Please check briefly. Nothing is deleted – existing sources are only switched to the app.",
 "Bitte zuerst den FACEIT API-Key eintragen und speichern.": "Please enter and save the FACEIT API key first.",
 "Blaue Zeilen kommen direkt aus den Overlays (z. B. aus OBS) – bei Problemen hier „Kopieren“ und mitschicken.": "Blue lines come directly from the overlays (e.g. from OBS) – if there are problems, “Copy” here and send it along.",
 "Blende": "Fade",
 "Browserquelle (": "browser source (",
 "Browserquelle „{}“ anlegen ({}, 1920 × 1080, 60 fps)": "Create browser source “{}” ({}, 1920 × 1080, 60 fps)",
 "Browserquellen direkt von DACH CS · ohne bewegte Übergänge": "Browser sources directly from DACH CS · without animated transitions",
 "Browserquellen in OBS:": "Browser sources in OBS:",
 "Caster & Gast": "Casters & guest",
 "Caster & Kameras": "Casters & cameras",
 "Caster – große Knöpfe": "Caster – big buttons",
 "Caster-Namen eintragen": "Enter caster names",
 "Casting-App schließen?": "Close the Casting-App?",
 "Cleanfeed · AN": "Cleanfeed · ON",
 "Cleanfeed-Szene anlegen?": "Create cleanfeed scene?",
 "Cleanfeed-Szene in OBS anlegen": "Create cleanfeed scene in OBS",
 "Clips / Browser-Rahmen": "Clips / browser frame",
 "Contentpause": "Content break",
 "CS2 neu starten": "Restart CS2",
 "CS2-Live-Daten": "CS2 live data",
 "CS2-Livedaten": "CS2 live data",
 "CS2-Ordner nicht gefunden. „Ordner selbst wählen …“ nutzen. (Kopie liegt in:": "CS2 folder not found. Use “Browse folders …”. (A copy is in:",
 "DACH CS – eigener Stil": "DACH CS – own style",
 "DACH CS – offiziell": "DACH CS – official",
 "DACH CS – Offiziell": "DACH CS – official",
 "DACH-CS-Zugang löschen?": "Delete DACH CS access?",
 "Danach funktionieren FACEIT-Abfragen erst wieder mit einem neuen Schlüssel.": "FACEIT requests will then only work again with a new key.",
 "Darstellung": "Display",
 "das aktuelle Map-Veto": "the current map veto",
 "Das App-Fenster ist stumm. Der Stream in OBS ist davon nicht betroffen.": "The app window is muted. The stream in OBS is not affected.",
 "Das ist nicht der CS2-Ordner. Er endet auf „game\\csgo\\cfg“.": "This is not the CS2 folder. It ends with “game\\csgo\\cfg”.",
 "Das Overlay": "The overlay",
 "das Overlay": "the overlay",
 "Das passiert jetzt in OBS": "This happens in OBS now",
 "Das sieht nicht wie ein DACH-CS-Key aus.": "That does not look like a DACH CS key.",
 "Das sieht nicht wie ein FACEIT-Schlüssel aus.": "That does not look like a FACEIT key.",
 "Das Veto kommt von FACEIT (Reiter „Match“ → FACEIT → „Daten holen“). Unten kannst du trotzdem korrigieren.": "The veto comes from FACEIT (tab “Match” → FACEIT → “Fetch data”). You can still correct it below.",
 "Datei für den Observer-PC herunterladen": "Download the file for the observer PC",
 "Datei in CS2 ablegen": "Put the file into CS2",
 "Datei konnte nicht gelesen werden.": "The file could not be read.",
 "Datei zu groß": "File too large",
 "Daten & Log": "Data & log",
 "Daten holen": "Fetch data",
 "Daten vom Observer-PC annehmen (Port 8788)": "Accept data from the observer PC (port 8788)",
 "Daten von FACEIT übernehmen?": "Take over data from FACEIT?",
 "Dauer": "Duration",
 "Dauer (Sek., 0 = bleibt)": "Duration (sec., 0 = stays)",
 "Der aktuelle Stand (Teams, Veto, Texte …) wird ersetzt. Die OBS-Einrichtung bleibt.": "The current state (teams, veto, texts …) is replaced. The OBS setup stays.",
 "der Gruppe": "of the group",
 "Der Schlüssel wird im Schlüsselbund des Systems gespeichert und nie wieder angezeigt – weder hier noch in Sicherungen, Sitzungen, Exporten oder im Log. Die App setzt ihn nur intern für FACEIT-Abfragen ein.": "The key is stored in the system keyring and never shown again – neither here nor in backups, sessions, exports or the log. The app only uses it internally for FACEIT requests.",
  "Die App öffnet Port 8788 im lokalen Netzwerk – ausschließlich für CS2-Spielstände mit deinem Schlüssel. Alles andere bleibt nur auf diesem PC erreichbar.": "The app opens port 8788 in the local network – only for CS2 game states with your key. Everything else stays reachable from this PC only.",
 "Die Browserquelle in OBS gibt Videos nicht zuverlässig wieder (in der Vorschau hier läuft es). Lass OBS das Video selbst abspielen – so wie eine normale Medienquelle, auch H.265 und AV1.": "The browser source in OBS does not play videos reliably (it plays in the preview here). Let OBS play the video itself – like a normal media source, also H.265 and AV1.",
 "Die Datei auf dem Observer-PC in dessen CS2-Ordner": "Put the file on the observer PC into its CS2 folder",
 "Die Datei ist zu groß für eine Sitzung.": "The file is too large for a session.",
 "Die Datei zum Herunterladen enthält Adresse und Schlüssel bereits.": "The file to download already contains the address and the key.",
 "die eingetragenen Spieler": "the entered players",
 "Die ersten 5 Spieler je Team erscheinen auf der Line-up-Seite.": "The first 5 players of each team appear on the line-up page.",
 "Die Nutzer-ID besteht nur aus Ziffern (z. B. 123).": "The user ID consists of digits only (e.g. 123).",
 "Die Standard-Presets (Bo1–Bo5) bleiben erhalten.": "The default presets (Bo1–Bo5) are kept.",
 "die Videos ab, gehen alle Formate, die OBS kann (auch H.265 und 4K) – die App legt dafür eine Medienquelle unter das Overlay und blendet sie in der Ingame-Szene automatisch aus. Spielt": "plays the videos, every format OBS supports works (also H.265 and 4K) – the app puts a media source below the overlay and hides it automatically in the ingame scene. If",
 "Die Vorschau zeigt die gewählte Szene. In OBS ändern sich die Overlays gleichzeitig mit.": "The preview shows the chosen scene. The overlays in OBS change at the same time.",
 "Diese App ist im Netzwerk erreichbar unter: {}": "This app can be reached in the network at: {}",
 "Diese Einträge werden durch die Daten aus dem Matchroom ersetzt:": "These entries are replaced by the data from the match room:",
 "diesem": "this",
 "Diesen Ordner nehmen": "Use this folder",
 "Dieser Browser erlaubt keinen Gerätezugriff.": "This browser does not allow device access.",
 "Dieses Theme auf Standard zurücksetzen": "Reset this theme to default",
 "Du hörst die Vorschau im App-Fenster – Videos, Kameras, Clips und Seiten. Der Stream bleibt unverändert.": "You hear the preview in the app window – videos, cameras, clips and pages. The stream stays unchanged.",
 "Dunkel": "Dark",
 "Dunkel (Balkenfarbe)": "Dark (bar colour)",
 "Duplizieren": "Duplicate",
 "Ecken der Kästen": "Box corners",
 "EIGENE": "OWN",
 "Eigene Contentpause": "Own content break",
 "Eigene Themes speichern sich automatisch. „Exportieren\" erzeugt eine Datei mit allen Farben, Logos und Bildern – zum Teilen oder als Sicherung.": "Your own themes are saved automatically. “Export\" creates a file with all colours, logos and images – to share or as a backup.",
 "Eigene Werte …": "Custom values …",
 "Eigenes Preset": "Custom preset",
 "Ein Fakt pro Zeile, z. B. „Die CT-Seite gewinnt hier 54 % der Runden.“": "One fact per line, e.g. “The CT side wins 54 % of the rounds here.”",
 "Ein- oder ausblenden": "Show or hide",
 "Einblendung": "Graphic",
 "EINBLENDUNG": "GRAPHIC",
 "Einblendung bearbeiten": "Edit graphic",
 "Einblendungen": "Graphics",
 "eine": "one",
 "Eine Browserquelle für alles": "One browser source for everything",
 "Eine Ebene höher": "One level up",
 "einer": "one",
 "Eingetragene Ergebnisse passen danach meist nicht mehr und werden gelöscht.": "Entered results usually no longer fit afterwards and are deleted.",
 "Einschalten": "Switch on",
 "Einstellungen": "Settings",
 "eintragen. Die Overlays brauchen kein Passwort.": ". The overlays need no password.",
 "Ende": "End",
 "Ende – Ergebnis": "End – result",
 "Ende – Titel": "End – title",
 "Ende – Unterzeile": "End – subtitle",
 "Entfernen": "Remove",
 "Entsperren": "Unlock",
 "Entsperren – {}": "Unlock – {}",
 "Ergebnis": "Result",
 "Ergebnis statt „VS\" anzeigen": "Show the result instead of “VS\"",
 "Ergebnisse aktualisieren": "Update results",
 "Ergebnisse ausblenden (nur, wer weiterkommt)": "Hide results (only who advances)",
 "Erst ab Runde": "Only from round",
 "Erst alle Spiele der aktuellen Runde als fertig markieren.": "First mark all matches of the current round as finished.",
 "Erst mit OBS verbinden (⚙ App-Einstellungen).": "Connect to OBS first (⚙ App settings).",
 "Erst unten Videos anhaken.": "Tick videos below first.",
 "Erste Schritte": "First steps",
 "erstellt die Steuerseite fehlende Szenen in OBS gleich mit der passenden Browserquelle – du musst dann nur noch Kameras & Co. hineinlegen. Hast du schon eigene Szenen, wählst du sie einfach in der Liste aus.": "the control page creates missing scenes in OBS right away with the matching browser source – you then only have to add cameras & co. If you already have your own scenes, just pick them in the list.",
 "Exportieren (Teilen)": "Export (share)",
 "FACEIT antwortet mit": "FACEIT answers with",
 "FACEIT API-Key (Server side, von developers.faceit.com)": "FACEIT API key (server side, from developers.faceit.com)",
 "FACEIT lehnt den API-Key ab (": "FACEIT rejects the API key (",
 "FACEIT-Fehler": "FACEIT error",
 "FACEIT-Schlüssel löschen?": "Delete FACEIT key?",
 "FACEIT-Team-ID": "FACEIT team ID",
 "FACEIT-Team-ID (optional)": "FACEIT team ID (optional)",
 "FACEIT-Turnier (Link oder ID)": "FACEIT tournament (link or ID)",
 "Fakt": "Fact",
 "Fakt wechselt alle (Sek.)": "Fact changes every (sec.)",
 "Fakten wechseln": "Rotate facts",
 "Farben, Logos und Sponsoren dieses Themes gehen verloren. Tipp: vorher exportieren.": "Colours, logos and sponsors of this theme will be lost. Tip: export it first.",
 "Farbige Linie zwischen Balken und Feld": "Coloured line between bar and field",
 "Farbvorlagen": "Colour presets",
 "Favorit": "Favourite",
 "Favoriten & aktive": "Favourites & active",
 "Fehler": "Error",
 "Fehler:": "Error:",
 "Felder": "Fields",
 "Fertig": "Done",
 "Feste Texte in den Overlays (Szenen-Überschriften, Statistiken). Eigene Texte bleiben, wie du sie eingetragen hast.": "Fixed texts in the overlays (scene headings, statistics). Your own texts stay as you entered them.",
 "Format / Preset": "Format / preset",
 "Format wechseln?": "Change format?",
 "Freilos": "Bye",
 "Funktioniert bei „Gerät\" (Mikrofon) und bei VDO.Ninja-Links.": "Works with “Device\" (microphone) and with VDO.Ninja links.",
 "Füllen": "Fill",
 "Füllen = passend zugeschnitten, Ganz = komplettes Bild": "Fill = cropped to fit, Whole = complete image",
 "Für Ingame ist keine OBS-Szene zugeordnet.": "No OBS scene is assigned for ingame.",
 "Ganz": "Whole",
 "Ganz beenden": "Quit completely",
 "Ganzes Logo": "Whole logo",
 "Gast": "Guest",
 "Gefunden – zum Ablegen anklicken:": "Found – click to put the file there:",
 "Geg. CT": "Opp. CT",
 "Geg. T": "Opp. T",
 "Gerade": "Straight",
 "Gerät": "Device",
 "Gerät (Webcam/Capture)": "Device (webcam/capture)",
 "Geräte suchen": "Find devices",
 "Gespeicherte Sitzungen": "Saved sessions",
 "Gewonnene Maps automatisch als Punktestand der Teams": "Use won maps as the teams' score automatically",
 "Gleich geht's weiter": "Back in a moment",
 "Groß einblenden": "Show big",
 "Große Einblendung (Sekunden)": "Big graphic (seconds)",
 "Großer Titel": "Big title",
 "Gruppe im Overlay": "Group in the overlay",
 "Gruppe(n) mit Tabelle": "group(s) with table",
 "Gruppen": "Groups",
 "Gruppen (GSL, je 4 Teams)": "Groups (GSL, 4 teams each)",
 "Gruppen mit Tabelle (jeder gegen jeden)": "Groups with table (round robin)",
 "Größe der Oberfläche": "Interface size",
 "Hardwarebeschleunigung für Browserquellen": "hardware acceleration for browser sources",
 "Head-to-Head Team A": "Head-to-head team A",
 "Head-to-Head Team B": "Head-to-head team B",
 "hebt es im Overlay hervor und zeigt sein Profil.": "highlights it in the overlay and shows its profile.",
 "Hell": "Light",
 "Hell (Feldfarbe)": "Light (field colour)",
 "Hell / Dunkel umschalten": "Toggle light / dark",
 "herunterladen": "download",
 "Hervorhebung aufheben": "Remove highlight",
 "hier": "here",
 "Hier ablegen": "Put it here",
 "Hintergrund": "Background",
 "Hintergrund (Clips / Drohnenaufnahmen)": "Background (clips / drone footage)",
 "Hintergrund, wenn keine Videos laufen": "Background when no videos play",
 "Hintergrund-Video (OBS spielt ab)": "Background video (OBS plays)",
 "Hintergrund-Video in OBS:": "Background video in OBS:",
 "Hinweis": "Notice",
 "Häkchen = Szene erscheint im Reiter": "Tick = scene appears in the tab",
 "Höchstens 32 Teams.": "At most 32 teams.",
 "ID und Key findest du im DACH-CS-Nutzerbereich unter Casting → Browserquellen. Beide werden im Schlüsselbund des Systems gespeichert und nie wieder angezeigt.": "You find the ID and key in the DACH CS user area under Casting → Browserquellen. Both are stored in the system keyring and never shown again.",
 "Im Overlay zeigen": "Show in the overlay",
 "Im Reiter Live anzeigen": "Show in the Live tab",
 "Im Spiel": "In the match",
 "im Veto": "in veto",
 "Import & Sitzungen": "Import & sessions",
 "Import fehlgeschlagen:": "Import failed:",
 "Importieren …": "Import …",
 "Importiertes Theme": "Imported theme",
 "In der Ingame-Szene wird sie nicht eingefügt": "It is not added to the ingame scene",
 "In der Szene „Ingame“ wird sie automatisch ausgeblendet": "In the scene “Ingame” it is hidden automatically",
 "In diesem Ordner suchen …": "Search in this folder …",
 "In Intro, Pause und Ende anzeigen": "Show in intro, break and end",
 "In OBS anlegen": "Create in OBS",
 "In OBS ausführen": "Run in OBS",
 "In OBS einrichten": "Set up in OBS",
 "In OBS entsteht (oder wird erneuert) „Cast – Cleanfeed“ mit diesen Quellen aus „{}“:": "OBS gets (or renews) “Cast – Cleanfeed” with these sources from “{}”:",
 "In OBS gibt es dann nur": "In OBS there is then only",
 "In OBS muss dafür der Kamerazugriff für Browserquellen erlaubt sein – siehe Anleitung (README).": "In OBS camera access for browser sources must be allowed for this – see the manual.",
 "In OBS wurde noch keine Browserquelle gefunden.": "No browser source found in OBS yet.",
 "In {} direkt unter das Overlay legen, bildfüllend": "Put it in {} directly below the overlay, full screen",
 "In „{}“ entsteht „{}“ – nur der Ton von {}, regelbar wie jede OBS-Quelle. Im Overlay wird sein Ton stumm, damit nichts doppelt läuft.": "“{}” gets “{}” – only the audio of {}, adjustable like any OBS source. Its audio is muted in the overlay so nothing plays twice.",
 "In „{}“ liegt außer den Grafiken der App nichts – zuerst die Spielaufnahme dort einfügen.": "“{}” contains nothing besides the app's graphics – add the game capture there first.",
 "Ingame / Bounty": "Ingame / bounty",
 "Inhalt": "Content",
 "Interaktion Duo": "Interaction duo",
 "Interaktion Single": "Interaction single",
 "Interview-Gast": "Interview guest",
 "Interview-Schild": "Interview badge",
 "Jede Einblendung hat eigene Einstellungen (Pfeil links): Dauer, Wiederholung, Position, Szenen. Über „Mehr“ (drei Punkte) duplizieren, verschieben oder löschen.": "Every graphic has its own settings (arrow on the left): duration, repeat, position, scenes. Use “More” (three dots) to duplicate, move or delete.",
 "Kamera- und Inhalts-Rahmen anpassen": "Adjust camera and content frames",
 "Kameras & Quellen": "Cameras & sources",
 "kein FACEIT-Schlüssel gespeichert": "no FACEIT key saved",
 "kein FACEIT-Schlüssel gespeichert (⚙ App-Einstellungen → Verbindungen & Zugänge)": "no FACEIT key saved (⚙ App settings → Connections & access)",
 "Kein gültiger Matchroom-Link.": "Not a valid match room link.",
 "Kein Ordner passt.": "No folder matches.",
 "Kein Team hat eine FACEIT-Team-ID.": "No team has a FACEIT team ID.",
 "Kein Team hervorheben": "Highlight no team",
 "Kein Zugriff erlaubt (": "No access allowed (",
 "keine": "none",
 "Keine Browserquelle der App in OBS gefunden.": "No browser source of the app found in OBS.",
 "Keine Kamera gefunden.": "No camera found.",
 "Keine neuen Daten seit": "No new data for",
 "Keine OBS-Szene zugeordnet (Setup → Szenen einrichten)": "No OBS scene assigned (Setup → Set up scenes)",
 "Keine passende OBS-Szene gefunden – erst „Szenen einrichten“.": "No matching OBS scene found – “Set up scenes” first.",
 "Keine passenden Spiele gefunden – stimmen die FACEIT-Team-IDs?": "No matching matches found – are the FACEIT team IDs right?",
 "keine Szene (erst Szenen einrichten)": "no scene (set up scenes first)",
 "keine Theme-Datei der Casting-App": "not a theme file of the Casting-App",
 "Keine Unterordner.": "No subfolders.",
 "Keine Verbindung zu FACEIT – Internet prüfen (Details im Reiter Log).": "No connection to FACEIT – check the internet (details in the Log tab).",
 "Key einfügen …": "Paste key …",
 "Klick auf ein Team": "Click on a team",
 "Komplettes Logo oben links (ersetzt Quadrat + Schriftzug)": "Complete logo top left (replaces square + lettering)",
 "Kopieren": "Copy",
 "Kürzel": "Short name",
 "Die Paarungen kommen von FACEIT – „Ergebnisse aktualisieren“ holt neue Runden.": "The pairings come from FACEIT – “Update results” fetches new rounds.",
 "Swiss wie bei FACEIT": "Swiss like FACEIT",
 "✓ Map beenden?": "✓ Finish map?",
 "Ein Team hat die Map gewonnen – als „Fertig“ eintragen": "A team has won the map – mark it as “Done”",
 "Kürzel – das Overlay zeigt es, wenn der Name nicht ohne starkes Verkleinern passt": "Short name – the overlay shows it when the name does not fit without heavy shrinking",
 "Lade Daten von FACEIT …": "Loading data from FACEIT …",
 "Lade Ergebnisse …": "Loading results …",
 "Lade Runden für die Rundendifferenz ({} von {}) …": "Loading rounds for the round difference ({} of {}) …",
 "Lade Spiele …": "Loading matches …",
 "Lade Statistiken …": "Loading statistics …",
 "Lade Team {} von {} (Logo, Spieler, Statistik) …": "Loading team {} of {} (logo, players, statistics) …",
 "Lade Turnier …": "Loading tournament …",
 "Laden": "Load",
 "Laden (.json)": "Load (.json)",
 "Laptop / neben OBS": "Laptop / next to OBS",
 "Lauftext – eine Meldung pro Zeile": "Ticker – one message per line",
 "Lauftext-Einleitung": "Ticker intro",
 "Lauftexte & Titel": "Tickers & title",
 "Laufwerke": "Drives",
 "Lautstärke im App-Fenster": "Volume in the app window",
 "Lautstärke {}": "Volume {}",
 "Layout bearbeiten": "Edit layout",
 "LAYOUT BEARBEITEN": "EDIT LAYOUT",
 "Layout bearbeiten beenden": "Stop editing the layout",
 "leer": "empty",
 "Leer (OBS-Quelle darüber)": "Empty (OBS source on top)",
 "Leeren": "Clear",
 "legen": "",
 "legen, dann hier anhaken. Sie laufen nacheinander in Schleife.": ", then tick them here. They play one after another in a loop.",
 "legen. Beim ersten Empfang fragt Windows auf": ". On the first reception Windows asks on",
 "Legt „Cast – Cleanfeed“ an: dieselben Quellen wie in der Ingame-Szene (z. B. Spielaufnahme, Ton), aber ohne die Grafiken der App. Ausgeben z. B. über OBS → Virtuelle Kamera (Ausgabe „Szene“), NDI oder Source Record.": "Creates “Cast – Cleanfeed”: the same sources as in the ingame scene (e.g. game capture, audio), but without the app's graphics. Output it e.g. via OBS → Virtual Camera (output “Scene”), NDI or Source Record.",
 "Letzte 5 Matches": "Last 5 matches",
 "Letzte 5 · Team A": "Last 5 · team A",
 "Letzte 5 · Team B": "Last 5 · team B",
 "Links": "Left",
 "Links Mitte": "Centre left",
 "Links neben der Vorschau andocken": "Dock left of the preview",
 "Links oben": "Top left",
 "Links unten": "Bottom left",
 "Logo entfernen": "Remove logo",
 "Logo in den Szenen (gilt für alle Themes) – „Auto\" zeigt nur das Icon, wenn das ganze Logo nicht passt": "Logo in the scenes (for all themes) – “Auto\" shows only the icon when the whole logo does not fit",
 "Logo wählen": "Choose logo",
 "Logo-Bild auf dunklem Kasten zeigen": "Show the logo image on a dark box",
 "Logo-Feld": "Logo field",
 "Logo-Feld: Org- oder Streamer-Logo (entfernen = kein Logo-Feld)": "Logo field: org or streamer logo (remove = no logo field)",
 "Logos am besten als PNG mit durchsichtigem Hintergrund. Die Liste gilt für das gewählte Theme – jede Liga hat ihre eigenen Sponsoren.": "Logos work best as PNG with a transparent background. The list belongs to the chosen theme – every league has its own sponsors.",
 "lässt sich nicht lesen": "cannot be read",
 "läuft": "running",
 "Läuft": "Running",
 "Läuft seit": "Running since",
 "Löschen": "Delete",
 "Manuell": "Manual",
 "Map steht im Veto zur Auswahl": "Map is available in the veto",
 "Map {} von {}{}": "Map {} of {}{}",
 "Map-Fakt": "Map fact",
 "Map-Fakten ({})": "Map facts ({})",
 "Map-Pool zurücksetzen?": "Reset map pool?",
 "Map-Veto & Serie": "Map veto & series",
 "Match nicht gefunden.": "Match not found.",
 "Matchroom-Link": "Match room link",
 "Medienquelle": "media source",
 "Mehr Einstellungen": "More settings",
 "Mehr: duplizieren, verschieben, löschen": "More: duplicate, move, delete",
 "Mein bisheriges Layout": "My previous layout",
 "Mein Layout": "My layout",
 "MEINE": "MINE",
 "Mindestens 2 Teams eintragen.": "Enter at least 2 teams.",
 "Minuten": "Minutes",
 "mit Gast": "with guest",
 "Mitgelieferte Themes lassen sich nicht löschen – nur unter „Theme anpassen“ zurücksetzen.": "Bundled themes cannot be deleted – only reset under “Customise theme”.",
 "Mitte oben": "Top centre",
 "Mitte unten": "Bottom centre",
 "Musik": "Music",
 "Musik (Spotify über Tuna)": "Music (Spotify via Tuna)",
 "Musik-Anzeige über Tuna": "Music display via Tuna",
 "Musik:": "Music:",
 "Musik: aus": "Music: off",
 "Musik: bereit": "Music: ready",
 "Musik: Tuna aus": "Music: Tuna off",
 "Musik: –": "Music: –",
 "Nach dem Spiel": "After the match",
 "Nach einem Update lädt die App die Overlays in OBS automatisch neu, sobald sie mit OBS verbunden ist.": "After an update the app reloads the overlays in OBS automatically as soon as it is connected to OBS.",
 "Nach oben": "Move up",
 "nach oben": "up",
 "Nach unten": "Move down",
 "nach unten": "down",
 "Nachtviolett": "Night violet",
 "Name / Rolle": "Name / role",
 "Name der Sitzung (z. B. „DACH CS Woche 3“):": "Name of the session (e.g. “DACH CS week 3”):",
 "Name des Themes": "Theme name",
 "Name des Turniers": "Tournament name",
 "Name für das Preset:": "Name of the preset:",
 "Name in der Liste": "Name in the list",
 "nebeneinander": "side by side",
 "Netzwerk-Empfang einschalten": "Switch on network reception",
 "Netzwerk-Empfang einschalten?": "Switch on network reception?",
 "Neu starten": "Restart",
 "Neue Map": "New map",
 "Neue Szenen:": "New scenes:",
 "Neue Version": "New version",
 "Neues Theme": "New theme",
 "nicht fürs Streaming optimiert (HandBrake: „Web Optimized“)": "not optimised for streaming (HandBrake: “Web Optimized”)",
 "Nicht mit OBS verbunden – ⚙ App-Einstellungen → Verbindung zu OBS.": "Not connected to OBS – ⚙ App settings → Connection to OBS.",
 "Nicht mit OBS verbunden.": "Not connected to OBS.",
 "nicht verbunden": "not connected",
 "Nichts gefunden.": "Nothing found.",
 "Nichts gefunden. Pfad bitte direkt eingeben oder „Ordner durchsuchen …“.": "Nothing found. Please enter the path directly or “Browse folders …”.",
 "Niederlage": "Loss",
 "Niederlage mit Map-Gewinn": "Loss with a map won",
 "Niederlagen bis raus": "Losses to be out",
 "Noch keine Daten von CS2": "No data from CS2 yet",
 "Noch keine gepickten Maps – erst das Map-Veto ausfüllen.": "No picked maps yet – fill in the map veto first.",
 "Noch keine Videos im Ordner.": "No videos in the folder yet.",
 "Noch nicht in OBS eingerichtet – „In OBS einrichten“ klicken.": "Not set up in OBS yet – click “Set up in OBS”.",
 "Nur die gespeicherte Anordnung wird gelöscht.": "Only the saved arrangement is deleted.",
 "Nur Favoriten": "Favourites only",
 "Nur Fenster schließen": "Close window only",
 "nur für diese Sitzung": "for this session only",
 "Nur Icon": "Icon only",
 "Nur in diesen Szenen (keine gewählt = überall)": "Only in these scenes (none chosen = everywhere)",
 "Nur in Ingame: alle Grafiken ausblenden – im Programm bleibt nur das Spielbild": "Ingame only: hide all graphics – only the game stays on program",
 "nur Warnungen & Fehler": "warnings & errors only",
 "Nutzer-ID": "User ID",
 "Nutzer-ID und Key werden aus der App entfernt. Die DACH-Browserquellen in OBS zeigen dann einen Hinweis statt der Grafiken.": "User ID and key are removed from the app. The DACH browser sources in OBS then show a notice instead of the graphics.",
 "Nächste 5 Matches": "Next 5 matches",
 "Nächste 5 · Team A": "Next 5 · team A",
 "Nächste 5 · Team B": "Next 5 · team B",
 "nächste in": "next in",
 "Nächste Runde auslosen": "Draw the next round",
 "Oberfläche": "Interface",
 "Oberfläche, Dialoge und Tray-Menü. Die App lädt danach neu.": "Interface, dialogs and tray menu. The app reloads afterwards.",
 "OBS antwortet nicht:": "OBS does not answer:",
 "OBS spielt ab – einrichten": "Let OBS play it – set up",
 "OBS verbinden": "Connect OBS",
 "OBS – empfohlen für H.265 & 4K": "OBS – recommended for H.265 & 4K",
 "OBS → Werkzeuge → WebSocket-Server-Einstellungen: „WebSocket-Server aktivieren\". Port und Passwort (unter „Verbindungsinformationen anzeigen\") nur": "OBS → Tools → WebSocket Server Settings: “Enable WebSocket server\". Enter port and password (under “Show Connect Info\") only",
 "obs-browser fehlt – OBS aktualisieren": "obs-browser is missing – update OBS",
 "OBS-Szene „{}“ fehlt – Setup → Aussehen → „In OBS einrichten“": "OBS scene “{}” is missing – Setup → Appearance → “Set up in OBS”",
 "OBS-Szene:": "OBS scene:",
 "OBS-Verbindung": "OBS connection",
 "OBS: nicht verbunden": "OBS: not connected",
 "OBS: Passwort falsch": "OBS: wrong password",
 "OBS: verbinde …": "OBS: connecting …",
 "OBS: verbunden": "OBS: connected",
 "oder bis Uhrzeit": "or until time of day",
 "Oder eigene Schriftdatei (.ttf/.otf/.woff2) – vorher in den": "Or your own font file (.ttf/.otf/.woff2) – first put it into the",
 "Oder Pfad direkt eingeben": "Or enter the path directly",
 "Oder Schriftzug als Bild (ersetzt die zwei Zeilen)": "Or lettering as an image (replaces the two lines)",
 "Offene Spiele unter der Tabelle zeigen": "Show open matches below the table",
 "Orchidee": "Orchid",
 "Ordner": "Folders",
 "Ordner durchsuchen …": "Browse folders …",
 "Ordner filtern": "Filter folders",
 "Ordner nicht gefunden oder kein Schreibzugriff.": "Folder not found or no write access.",
 "Ordner nicht gefunden oder kein Zugriff": "Folder not found or no access",
 "Ordner öffnen": "Open folder",
 "Overlay (Clips, Seiten, Videos im Overlay)": "Overlay (clips, pages, videos in the overlay)",
 "Overlays in OBS neu laden": "Reload overlays in OBS",
 "Passwort": "Password",
 "Passwort löschen": "Delete password",
 "Pause – Titel": "Break – title",
 "Pause – Unterzeile": "Break – subtitle",
 "Pausescreen": "Break screen",
 "PC nach der Firewall: „Private Netzwerke“ erlauben (oder Port 8788 freigeben). Angenommen werden nur Daten mit deinem Schlüssel.": "PC about the firewall: allow “Private networks” (or open port 8788). Only data with your key is accepted.",
 "Platte hinter dem Schriftzug": "Plate behind the lettering",
 "Plätze, die weiterkommen": "Places that advance",
 "Preset löschen": "Delete preset",
 "Preset „{}“ löschen?": "Delete preset “{}”?",
 "PROGRAMM": "PROGRAM",
 "Protokoll": "Log",
 "Punkt abziehen Team A": "Remove a point from team A",
 "Punkt abziehen Team B": "Remove a point from team B",
 "Punkt Team A": "Point for team A",
 "Punkt Team B": "Point for team B",
 "Punkteregel": "Points rule",
 "Punktestand": "Score",
 "Quelle": "Source",
 "Rahmen in der Vorschau zeigen": "Show frames in the preview",
 "Rechts": "Right",
 "Rechts andocken": "Dock on the right",
 "rechts andocken": "dock on the right",
 "Rechts Mitte": "Centre right",
 "Rechts neben der Vorschau andocken": "Dock right of the preview",
 "Rechts oben": "Top right",
 "Rechts unten": "Bottom right",
 "Regulär": "Regular",
 "Reihenfolge bei Punktgleichheit: direkter Vergleich → Rundendifferenz (RD, von FACEIT) → Siege. Die Punkte rechnet die App selbst – so lässt sich jede Turnierregel abbilden.": "Order on equal points: head-to-head → round difference (RD, from FACEIT) → wins. The app calculates the points itself – so any tournament rule can be mapped.",
 "Reihenfolge ziehen, Haken = Szene wird angezeigt": "Drag to reorder, tick = scene is shown",
 "Reiter": "Tabs",
 "REITER": "TAB",
 "Reiter-Spalte": "Tab column",
 "Reiter-Spalte auf die andere Seite": "Move the tab column to the other side",
 "Reiter-Spalte sperren": "Lock the tab column",
 "Reiter-Spalte sperren – Reihenfolge und Breite bleiben, wie sie sind": "Lock the tab column – order and width stay as they are",
 "Richte OBS ein …": "Setting up OBS …",
 "Runde": "Round",
 "Runde für Runde aufdecken – bis Runde": "Reveal round by round – up to round",
 "Rückgängig": "Undo",
 "Schieben": "Slide",
 "Schließen": "Close",
 "Schließen oder beenden": "Close or quit",
 "Schließen oder ganz beenden": "Close or quit completely",
 "Schlüssel einfügen …": "Paste key …",
 "Schlüssel gelöscht.": "Key deleted.",
 "Schlüssel löschen": "Delete key",
 "Schlüssel speichern": "Save key",
 "Schnitt": "Cut",
 "Schrift auf Feldern": "Text on fields",
 "Schrift extra kräftig": "Extra bold text",
 "Schrift in Balken": "Text in bars",
 "Schriftart (auf dem PC installiert)": "Font (installed on the PC)",
 "Schriften-Ordner": "Fonts folder",
 "Schriftzug Zeile 1": "Lettering line 1",
 "Schritt entfernen": "Remove step",
 "Schritt {}": "Step {}",
 "Schritt {}: {}": "Step {}: {}",
 "Schwelle (niedriger = empfindlicher)": "Threshold (lower = more sensitive)",
 "Seite": "Page",
 "Seite –": "Side –",
 "Seiten-Dock": "Side dock",
 "Seiten-Dock auf die andere Seite": "Move the side dock to the other side",
 "Seiten-Dock sperren": "Lock the side dock",
 "Seiten-Dock sperren – dann ändert sich hier nichts mehr": "Lock the side dock – then nothing changes here any more",
 "Sekunden": "seconds",
 "Sendung – alles in einer Browserquelle": "Broadcast – everything in one browser source",
 "Serie": "Series",
 "Serie & Map-Ergebnisse": "Series & map results",
 "Setzen": "Set",
 "Sichern (.json)": "Back up (.json)",
 "sichtbar · noch": "visible · for",
 "Sieg 2 · Niederlage mit Map-Gewinn 1 · Niederlage 0": "Win 2 · loss with a map won 1 · loss 0",
 "Sieg 2:0 = 3 · Sieg 2:1 = 2 · Niederlage 1:2 = 1 · 0:2 = 0": "Win 2:0 = 3 · win 2:1 = 2 · loss 1:2 = 1 · 0:2 = 0",
 "Sieg 3 · Niederlage 0": "Win 3 · loss 0",
 "Sieg 3 · Niederlage mit Map-Gewinn 1 · Niederlage 0": "Win 3 · loss with a map won 1 · loss 0",
 "Sieg mit Map-Verlust": "Win with a map lost",
 "Sieg ohne Map-Verlust": "Win without a map lost",
 "Siege bis weiter": "Wins to advance",
 "Sitzung „{}“ laden?": "Load session “{}”?",
 "Sitzung „{}“ löschen?": "Delete session “{}”?",
 "Sitzungen": "Sessions",
 "Sitzungen können in diesem Browser nicht gespeichert werden.": "Sessions cannot be saved in this browser.",
 "So geht's:": "How it works:",
 "Speichern": "Save",
 "Speichern fehlgeschlagen": "Saving failed",
 "Speichern fehlgeschlagen:": "Saving failed:",
 "Speichern unter …": "Save as …",
 "Sperren": "Lock",
 "Sperren – {}": "Lock – {}",
 "Spiegeln": "Mirror",
 "Spielbild: in OBS die Spielaufnahme in „Cast – Sendung“ unter die Browserquelle legen.": "Game picture: in OBS put the game capture into “Cast – Sendung” below the browser source.",
 "Spiele – Ergebnis eintragen, Haken = fertig.": "Matches – enter the result, tick = finished.",
 "Spieler": "Players",
 "Spieler (live)": "Player (live)",
 "Spieler „{}“": "Player “{}”",
 "Spieler, mit Komma getrennt": "Players, separated by commas",
 "Spielt": "If",
 "Spieltag": "Match day",
 "Sponsor groß einblenden:": "Show sponsor big:",
 "Sponsor-Kasten zeigen in:": "Show the sponsor box in:",
 "Sponsoren": "Sponsors",
 "Sponsoren anzeigen": "Show sponsors",
 "Sponsoren für {}": "Sponsors for {}",
 "Sponsoren zusätzlich im Lauftext nennen": "Also name sponsors in the ticker",
 "Sprache der App": "App language",
 "Sprache der Overlays": "Overlay language",
 "Sprecher-Anzeige: Schild leuchtet, wenn jemand spricht": "Speaker indicator: the name badge lights up when someone speaks",
 "Später": "Later",
 "Standard": "Default",
 "Standard wiederherstellen": "Restore defaults",
 "Standard-Dauer für neue (Sek., 0 = bleibt)": "Default duration for new ones (sec., 0 = stays)",
 "Standard-Reihenfolge": "Default order",
 "Stats & Liga": "Stats & league",
 "Stats & Turnier": "Stats & tournament",
 "Stats über dem Spiel (während Ingame) ausblenden nach": "Hide stats over the game (during ingame) after",
 "Strg K": "Ctrl K",
 "Stumm": "Mute",
 "Suche läuft (höchstens ein paar Sekunden) …": "Searching (a few seconds at most) …",
 "Suchen": "Search",
 "Suchen & Befehle": "Search & commands",
 "Suchen und Befehle": "Search and commands",
 "Szene": "Scene",
 "SZENE": "SCENE",
 "Szene mit": "scene with",
 "Szene „Cast – Sendung“ in OBS anlegen": "Create the scene “Cast – Sendung” in OBS",
 "Szene „{}“ anlegen": "Create scene “{}”",
 "Szene, Einblendung, Bereich oder Befehl …": "Scene, graphic, area or command …",
 "Szenen": "Scenes",
 "Szenen & OBS": "Scenes & OBS",
 "Szenen einrichten": "Set up scenes",
 "Szenen in OBS anlegen": "Create scenes in OBS",
 "Szenen per Klick wechseln": "Switch scenes with a click",
 "Szenen, Einblendungen, Bereiche und Befehle finden": "Find scenes, graphics, areas and commands",
 "Tabelle": "Table",
 "Tabelle zeigen": "Show table",
 "Team A spielt gerade": "Team A is currently playing",
 "Team hervorheben": "Highlight team",
 "Team-Statistiken von FACEIT laden": "Load team statistics from FACEIT",
 "Teamname": "Team name",
 "Teams & Ergebnis": "Teams & result",
 "Teams & Spieler": "Teams & players",
 "Teams eintragen": "Enter teams",
 "Teams und Format bleiben, alle Spielstände (und Swiss-Runden) werden geleert.": "Teams and format stay, all scores (and Swiss rounds) are cleared.",
 "Teams zuordnen": "Assign teams",
 "Teams – Reihenfolge = Setzliste (bis 32). Spieler mit Komma trennen.": "Teams – order = seeding (up to 32). Separate players with commas.",
 "Teams „{}“ und „{}“ samt Logos": "Teams “{}” and “{}” including logos",
 "Teams, Aufbau und Ergebnisse werden durch die Daten von FACEIT ersetzt.": "Teams, structure and results are replaced by the data from FACEIT.",
 "Teams, Texte, Veto, Spieler, Sponsoren, Themes und Einstellungen gehen auf Standard. Tipp: vorher „Sichern (.json)“.": "Teams, texts, veto, players, sponsors, themes and settings go back to default. Tip: “Back up (.json)” first.",
 "Tempo des Lauftexts": "Ticker speed",
 "Theme anpassen": "Customise theme",
 "Theme der Liga wählen": "Choose the league's theme",
 "Theme zurücksetzen?": "Reset theme?",
 "Theme {}": "Theme {}",
 "Theme „{}“ gelöscht": "Theme “{}” deleted",
 "Theme „{}“ löschen?": "Delete theme “{}”?",
 "Timer & Texte": "Timer & texts",
 "Timer (Intro)": "Timer (intro)",
 "Timer (Pause)": "Timer (break)",
 "Timer pausieren": "Pause timer",
 "Timer starten": "Start timer",
 "Titel der Sponsoren-Szene": "Title of the sponsor scene",
 "Ton": "Audio",
 "Ton im App-Fenster": "Audio in the app window",
 "Ton wird direkt in OBS geregelt (wie im OBS-Mixer) – dafür mit OBS verbinden (⚙ App-Einstellungen).": "Audio is controlled directly in OBS (like in the OBS mixer) – connect to OBS for this (⚙ App settings).",
 "Tuna-Adresse": "Tuna address",
 "Turnier": "Tournament",
 "Turnier aus FACEIT übernehmen?": "Import the tournament from FACEIT?",
 "Turnier live": "Tournament live",
 "Turnier übernehmen": "Import tournament",
 "Turnierbaum": "Bracket",
 "und": "and",
 "und das Match als": "and open the match as a",
 "und ohne Ton": "and without audio",
 "Unentschieden": "Draw",
 "Ungültiges Passwort": "Invalid password",
 "Unter der Vorschau": "Below the preview",
 "Unter der Vorschau andocken": "Dock below the preview",
 "untereinander": "stacked",
 "VDO.Ninja / Link": "VDO.Ninja / link",
 "VDO.Ninja – Ton läuft noch im Overlay": "VDO.Ninja – audio still plays in the overlay",
 "VDO.Ninja-View-Link, Stream-ID oder beliebiger Link": "VDO.Ninja view link, stream ID or any link",
 "veraltet": "outdated",
 "Verbinden": "Connect",
 "Verbindung zu OBS": "Connection to OBS",
 "Verbindung zu OBS – Klick öffnet die Einstellungen": "Connection to OBS – click to open the settings",
 "Verbindungen anzeigen": "Show connections",
 "verbunden": "connected",
 "Verbundene Overlays": "Connected overlays",
 "Verbundene Overlays – Klick öffnet den Log": "Connected overlays – click to open the log",
 "verfügbar": "available",
 "verschlüsselt": "stored securely",
 "Verzögerung (ms)": "Delay (ms)",
 "Veto neu starten?": "Restart veto?",
 "Videos in den": "Put videos into the",
 "Videos und eigene Schriften legst du in deinen Dokumenten ab – die App liest sie von dort.": "Put videos and your own fonts into your documents – the app reads them from there.",
 "Videos-Ordner": "videos folder",
 "Videos-Ordner öffnen": "Open videos folder",
 "Videos: {} · Schriften: {} · Daten: {}": "Videos: {} · fonts: {} · data: {}",
 "vor": "ago",
 "Vor dem Spiel": "Before the match",
 "vor {} s": "{} s ago",
 "Vorbereitung": "Preparation",
 "Vorhandene Browserquelle „{}“ auf die App umstellen ({})": "Switch the existing browser source “{}” to the app ({})",
 "Vorhandene Quelle „{}“ bekommt die ausgewählten Videos": "Existing source “{}” gets the selected videos",
 "Vorhandene Quelle „{}“ wird durch eine {} ersetzt": "Existing source “{}” is replaced by a {}",
 "VORLAGEN": "PRESETS",
 "Vorschau": "Preview",
 "Vorschau = die Sendung, genau so wie in OBS (overlay.html).": "Preview = the broadcast, exactly like in OBS (overlay.html).",
 "Vorschau ein-/ausklappen": "Expand/collapse preview",
 "Vorschau-Dock": "Preview dock",
 "Vorschau-Dock oben/unten tauschen": "Swap the preview dock top/bottom",
 "Vorschau-Dock sperren": "Lock the preview dock",
 "Vorschau-Dock sperren – dann ändert sich hier nichts mehr": "Lock the preview dock – then nothing changes here any more",
 "Vorschau:": "Preview:",
 "wartet auf Szene": "waiting for scene",
 "Was in den Kamera-Rahmen erscheint:": "What appears in the camera frames:",
 "Wechsel alle … Sekunden": "Change every … seconds",
 "Wechsel fehlgeschlagen:": "Switch failed:",
 "Wechseln": "Change",
 "Wechseln zu:": "Switch to:",
 "Wechselt in overlay.html (eine Browserquelle). Rot = läuft gerade.": "Switches in overlay.html (one browser source). Red = currently live.",
 "Wer spielt die Videos ab?": "Who plays the videos?",
 "Werte in Pixeln auf 1920 × 1080. Singlecam ist aus dem echten DACH-Layout gemessen; die anderen sind Startwerte – mit „Rahmen zeigen“ in der Vorschau passend ausrichten.": "Values in pixels on 1920 × 1080. Singlecam is measured from the real DACH layout; the others are starting values – align them with “Show frames” in the preview.",
 "Wie bei FACEIT (übernommener Baum)": "Like FACEIT (imported bracket)",
 "wie in OBS": "like in OBS",
 "wie in OBS ({})": "like in OBS ({})",
 "Wie das System": "Like the system",
 "Wiedergabeliste": "playlist",
 "Wiederholen alle (Min., 0 = nie)": "Repeat every (min., 0 = never)",
 "Wischen": "Wipe",
 "Wo läuft CS2?": "Where does CS2 run?",
 "wählen": "choose",
 "wählen – oder in OBS unter Einstellungen → Erweitert → Quellen die": "– or in OBS under Settings → Advanced → Sources switch",
 "Während Ingame: erscheint über dem Spiel. Umschalt-Klick = ganze Szene wechseln.": "During ingame: appears over the game. Shift-click = switch the whole scene.",
 "z. B. D:\\SteamLibrary\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo\\cfg": "e.g. D:\\SteamLibrary\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo\\cfg",
 "z. B. Uniliga Playoffs": "e.g. Uniliga Playoffs",
 "Zeigen": "Show",
 "Zeigen:": "Show:",
 "Zeigt OBS das Video nur zeitweise (in der Vorschau hier läuft es)? Dann": "Does OBS show the video only at times (it plays in the preview here)? Then",
 "Zeile 1 groß, Zeile 2 klein in Akzentfarbe": "Line 1 large, line 2 small in accent colour",
 "Zeile 2": "Line 2",
 "Ziehen = Höhe ändern · Doppelklick = Höhe passend zum Inhalt": "Drag = change height · double click = fit height to content",
 "Ziehen, um die Breite zu ändern": "Drag to change the width",
 "Ziehen, um die Höhe zu ändern": "Drag to change the height",
 "Ziehen: links, unter oder neben die Vorschau": "Drag: left of, below or next to the preview",
 "Ziel ist der Ordner": "The target is the folder",
 "Zugang gelöscht.": "Access deleted.",
 "ZULETZT": "RECENT",
 "Zur Halbzeit tauscht die App die Seiten selbst. Heißen die Teams auf dem Server wie Team A/B (z. B. bei FACEIT), ordnet sie automatisch zu.": "At half time the app swaps the sides itself. If the teams on the server have the names of team A/B (e.g. on FACEIT), it assigns them automatically.",
 "Zur Szene „Cast – Sendung“ wechseln": "Switch to the scene “Cast – Sendung”",
 "Größe passt sich dem Fenster an": "Size follows the window",
 "Zurück auf automatische Größe": "Back to automatic size",
 "Zurücksetzen": "Reset",
 "Zusatz": "Extra line",
 "Zuschauer": "spectator",
 "Zwischen den Maps": "Between maps",
 "{} (fehlt in OBS)": "{} (missing in OBS)",
 "{} bannt": "{} bans",
 "{} entfernt": "{} removed",
 "{} Gerät(e) gefunden": "{} device(s) found",
 "{} pickt": "{} picks",
 "{} Szene(n) ohne OBS-Szene – Setup → Szenen einrichten → „In OBS anlegen\".": "{} scene(s) without an OBS scene – Setup → Set up scenes → “Create in OBS\".",
 "{} von {} verbunden": "{} of {} connected",
 "{} × {} – im Overlay lieber 1920 × 1080 (oder „OBS spielt ab“)": "{} × {} – in the overlay better 1920 × 1080 (or “OBS plays”)",
 "{} über dem Spiel (Ingame)": "{} over the game (ingame)",
 "{} „{}“ anlegen ({} Video{}, in Schleife)": "Create {} “{}” ({} video{}, looping)",
 "{}: eigene Tonquelle in OBS?": "{}: own audio source in OBS?",
 "{}: im Overlay nur mit Grafikkarten-Dekodierung – sicherer: „OBS spielt ab“": "{}: in the overlay only with GPU decoding – safer: “OBS plays”",
 "· Observer-PC": "· observer PC",
 "· Update": "· update",
 "· {} · Runde {} · CT {} : {} T · {} Spieler": "· {} · round {} · CT {} : {} T · {} players",
 "· ⚠ kleiner als optimal ({} × {})": "· ⚠ smaller than optimal ({} × {})",
 "· ✓ scharf": "· ✓ sharp",
 "Öffnen": "Open",
 "öffnen (GOTV oder Observer-Slot) – nur dann liefert CS2 alle 10 Spieler.": "(GOTV or observer slot) – only then CS2 delivers all 10 players.",
 "Öffnen:": "Open:",
 "über dem Spiel (Ingame)": "over the game (ingame)",
 "Über der Vorschau": "Above the preview",
 "Über der Vorschau andocken": "Dock above the preview",
 "ÜBER SPIEL": "OVER GAME",
 "ÜBER SPIEL · AN": "OVER GAME · ON",
 "Übergang": "Transition",
 "Übergang beim nächsten Wechsel – was in beiden Szenen vorkommt (Logo, Lauftext, Match-Up, Kameras …) bleibt stehen oder gleitet an seinen neuen Platz": "Transition for the next switch – whatever is in both scenes (logo, ticker, match-up, cameras …) stays or glides to its new place",
 "Übergang, wenn nichts anderes gewählt": "Transition when nothing else is chosen",
 "Übergang:": "Transition:",
 "Übernehmen": "Take over",
 "Überschrift": "Heading",
 "Überschrift (optional)": "Heading (optional)",
 "Überschriften": "Headings",
 "– alte Version": "– old version",
 "– erst „Geräte suchen“ –": "– first “Find devices” –",
 "– für mehrere Videos bitte VLC installieren, sonst läuft nur das erste.": "– for several videos please install VLC, otherwise only the first one plays.",
 "– jetzt CS2 neu starten.": "– now restart CS2.",
 "– keine –": "– none –",
 "– nicht zugeordnet –": "– not assigned –",
 "– noch keine –": "– none yet –",
 "– oder": "– or",
 "– offen –": "– open –",
 "– wählen –": "– choose –",
 "„Erste Schritte\" wieder zeigen": "Show “First steps\" again",
 "„In OBS anlegen\"": "“Create in OBS\"",
 "„OBS spielt ab\"": "“OBS plays\"",
 "„{}“ zusätzlich in „{}“ einfügen": "Also add “{}” to “{}”",
 "↶ Rückgängig": "↶ Undo",
 "⇄ Teams tauschen": "⇄ Swap teams",
 "Links neben der Vorschau": "Left of the preview",
 "Zurück in den Reiter": "Back into the tab",
 "Rechts neben der Vorschau": "Right of the preview",
 "● CS2 · Runde {}": "● CS2 · round {}",
 "In den Reiter": "Into the tab",
 "⚙ App-Einstellungen": "⚙ App settings",
 "⚠ Speichern fehlgeschlagen": "⚠ Saving failed",
 "⚠ {} Problem(e):": "⚠ {} problem(s):",
 "✎ Anordnen": "✎ Arrange",
 "✓ Abgelegt in:": "✓ Saved in:",
 "✓ Das ist der CS2-Ordner.": "✓ This is the CS2 folder.",
 "✓ Fertig": "✓ Done",
 "✓ gespeichert": "✓ saved",
 "✓ Gespeichert ({}{}).": "✓ Saved ({}{}).",
 "✓ Gespeichert – nur für diese Sitzung (keine Verschlüsselung verfügbar).": "✓ Saved – for this session only (no secure storage available).",
 "✓ Key gespeichert – zum Ersetzen neuen einfügen": "✓ Key saved – paste a new one to replace it",
 "✓ Kopie angelegt.": "✓ Copy created.",
 "✓ Neues Theme angelegt – unter „Theme anpassen“ einrichten.": "✓ New theme created – set it up under “Customise theme”.",
 "✓ OBS spielt die Videos ab ({} „{}“ in {} Szene(n))": "✓ OBS plays the videos ({} “{}” in {} scene(s))",
 "✓ Runde {} ausgelost ({} Spiele).": "✓ Round {} drawn ({} matches).",
 "✓ Schlüssel gespeichert – zum Ersetzen neuen einfügen": "✓ Key saved – paste a new one to replace it",
 "✓ Statistiken für {} von {} Teams geladen.": "✓ Statistics loaded for {} of {} teams.",
 "✓ Theme „{}“ importiert.": "✓ Theme “{}” imported.",
 "✓ Verschlüsselt gespeichert. Der Schlüssel wird nicht wieder angezeigt.": "✓ Stored securely. The key will not be shown again.",
 "✓ Veto abgeschlossen": "✓ Veto complete",
 "✓ Videoauswahl an OBS übergeben": "✓ Video selection handed to OBS",
 "✓ {} Browserquelle(n) in OBS neu geladen": "✓ {} browser source(s) reloaded in OBS",
 "✓ {} Ergebnisse aktualisiert.": "✓ {} results updated.",
 "✓ {} Ergebnisse von FACEIT übernommen.": "✓ {} results imported from FACEIT.",
 "✓ Änderungen gehen direkt an alle Browserquellen in OBS": "✓ Changes go directly to all browser sources in OBS",
 "✓ Übernommen: {} Teams · {} · {} Ergebnisse.": "✓ Imported: {} teams · {} · {} results.",
 "✓ „Cast – Cleanfeed“ angelegt ({} Quelle{}). Ausgeben z. B. über die virtuelle Kamera mit Ausgabe „Szene“.": "✓ “Cast – Cleanfeed” created ({} source{}). Output it e.g. with the virtual camera, output type “Scene”.",
 "✓ „{}\" geladen": "✓ “{}\" loaded",
 "✓ „{}\" gespeichert": "✓ “{}\" saved",
 "✓ „{}“ exportiert (Download-Ordner).": "✓ “{}” exported (downloads folder).",
 "✗ OBS nimmt die Änderungen nicht an (": "✗ OBS does not accept the changes (",
 "Steuerseite im Browser öffnen": "Open control page in browser",
 "Browserquellen umstellen": "Update browser sources",
 "✓ Alle Browserquellen der App haben den Zugangsschlüssel.": "✓ All of the app's browser sources have the access key.",
 "{} Browserquelle(n) der App in OBS ohne Zugangsschlüssel: {}": "{} of the app's browser source(s) in OBS without access key: {}",
 "Browserquellen in OBS umstellen?": "Update browser sources in OBS?",
 "Seit Version 2.3 brauchen die Browserquellen der App einen Zugangsschlüssel – sonst fehlen die DACH-CS-Seiten. Beim Umstellen lädt jede Quelle einmal kurz neu (nicht während einer laufenden Szene im Stream).": "Since version 2.3 the app's browser sources need an access key – otherwise the DACH CS pages are missing. Each source reloads briefly once when updated (not while a scene is live on stream).",
 "„{}“ umstellen": "Update “{}”",
 "Umstellen": "Update",
 "Diese Steuerseite hat keinen Zugangsschlüssel und kann nichts ändern. Öffne sie aus der Casting-App (App-Fenster → ⚙ App-Einstellungen → Verbindung zu OBS → „Steuerseite im Browser öffnen“) oder nimm ohne Fenster die Adresse aus der Konsole.": "This control page has no access key and cannot change anything. Open it from the Casting-App (app window → ⚙ App settings → Connection to OBS → “Open control page in browser”) or, without window, use the address from the console.",
 "Abhören aus": "Monitor Off",
 "nur im Stream/der Aufnahme, nicht auf deinem Kopfhörer": "only in the stream/recording, not on your headphones",
 "nur auf deinem Kopfhörer, nicht im Stream": "only on your headphones, not in the stream",
 "im Stream und auf deinem Kopfhörer": "in the stream and on your headphones",
 "In OBS gibt es noch keine Quelle mit Ton – Setup → Szenen & OBS → „In OBS anlegen“.": "OBS has no source with audio yet – Setup → Scenes & OBS → “Create in OBS”.",
 "Die App antwortet nicht.": "The app does not respond.",
 "Bilanz {}": "Record {}",
 "Update": "Update",
 "Installiert:": "Installed:",
 "noch nicht gesucht": "not checked yet",
 "Nach Updates suchen": "Check for updates",
 "Jetzt aktualisieren": "Update now",
 "Download-Seite öffnen": "Open download page",
 "Bei jedem Start nach Updates suchen (fragt nur die Versionsliste bei GitHub ab)": "Check for updates at every start (only asks GitHub for the list of versions)",
 "Die neue Version wird von GitHub geladen, mit der Prüfsumme verglichen und installiert; die App startet danach neu. Einstellungen, Bilder und Zugänge bleiben. Nicht während einer laufenden Sendung aktualisieren.": "The new version is downloaded from GitHub, checked against its checksum and installed; the app then restarts. Settings, images and access data stay. Do not update during a live show.",
 "suche …": "checking …",
 "✓ aktuell": "✓ up to date",
 "Neue Version {} verfügbar": "New version {} available",
 "lade Version {} … {} %": "downloading version {} … {} %",
 "installiere Version {} – die App startet gleich neu": "installing version {} – the app restarts in a moment",
 "Update fehlgeschlagen: {}": "Update failed: {}",
 "Jetzt aktualisieren?": "Update now?",
 "Die App lädt die neue Version, beendet sich und startet neu. Overlays in OBS sind dabei kurz weg – nicht während einer laufenden Sendung.": "The app downloads the new version, quits and starts again. Overlays in OBS are gone for a moment – not during a live show.",
 "aktualisiert von v{}": "updated from v{}",
 "Szenenwechsel ist aus – oben den Haken setzen.": "Scene switching is off – tick the box above.",
 "Mehrere OBS-Szenen: erst mit OBS verbinden (⚙ App-Einstellungen) – oder unter Setup → Szenen & OBS „eine Browserquelle“ nutzen.": "Several OBS scenes: connect to OBS first (⚙ App settings) – or use “one browser source” under Setup → Scenes & OBS.",
 "✓ Runde {} ausgelost (1 Spiel).": "✓ Round {} drawn (1 match).",
 "Diagnose in allen Overlays einblenden – ⚠ auch im Stream sichtbar (nur zur Fehlersuche, danach wieder aus)": "Show diagnostics in all overlays – ⚠ also visible in the stream (for troubleshooting only, switch off afterwards)",
 "Overlay-Adresse kopieren": "Copy overlay address",
 "Für eine Browserquelle, die du selbst in OBS anlegst (1920 × 1080)": "For a browser source you create yourself in OBS (1920 × 1080)",
 "✓ Adresse kopiert – in OBS als Browserquelle (1920 × 1080) einfügen. Sie enthält den Zugangsschlüssel: nicht weitergeben.": "✓ Address copied – paste it into OBS as a browser source (1920 × 1080). It contains the access key: do not share it.",
 "Kopieren nicht möglich – „In OBS anlegen“ nutzen.": "Copying is not possible – use “Create in OBS”."
};
